[package]
name = "dht"
version = "0.1.0"
authors = ["95th <vargwin@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
data-encoding = "2.1.2"
ben =  { git = "https://github.com/95th/ben" }
anyhow = "1.0.28"
tokio-util = { version = "0.3.1", features = ["udp"] }
bytes = "0.5.4"
tokio = { version = "0.2.11", features = ["io-util", "net", "macros", "stream"] }
log = "0.4.8"
env_logger = "0.7.1"
bitflags = "1.2.1"
