[package]
name = "dht-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
slab = "0.4.5"
ben = { path = "../ben" }
hashbrown = "0.11.2"
log = "0.4.14"
anyhow = "1.0.44"
bitflags = "1.3.2"
rand = "0.8.4"
data-encoding = "2.3.2"
