[package]
name = "client-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.13"
anyhow = "1.0.38"
ben = { path = "../ben" }
bytes = "1.1.0"
sha1 = "0.6.0"
thiserror = "1.0.30"
url = "2.2.2"
data-encoding = "2.3.2"
